### ISSUE TITLE
How to fix price after tax? 

### ISSUE THREAD

**Issue by tdrabikdev** [LaravelDaily/laravel-invoices#101]
**Describe the bug**
Tax is rounded up and it give a wrong sum on invoice.

**To Reproduce**
```php
        $customer = new Buyer([
            'name'          => 'John Doe',
            'custom_fields' => [
                'email' => 'test@example.com',
            ],
        ]);

        $item = (new InvoiceItem())->title('Service 1')->pricePerUnit(8.33);

        $invoice = Invoice::make()
            ->buyer($customer)

            ->taxRate(20)
            ->addItem($item);

        return $invoice->stream();
```

**Expected behavior**
gross price £9.99,
 tax 20%, 
net price £8.33 
tax:£ 1.66
price on invoice £9.99

**Result**
gross price £9.99,
tax 20%, 
net price £8.33 
tax:£ 1.67
price on invoice £10.00

**Screenshots**

![image](https://user-images.githubusercontent.com/82902162/130674977-66983672-354a-4b1f-b288-ef96137634b2.png)

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Browser chrome

**Comment by mc0de** [comment]
Actually this is expected behavior, because 20% of 8.33 is 1.(6) so it gets rounded to 1.67
Specifically for this case and if it might be an issue for someone we provide override methods, but then you need to calculate taxes yourself and pass the result as a parameter

```PHP
<...>
        $invoice = Invoice::make()
            ->buyer($customer)
            ->totalTaxes(1.66)
            ->addItem($item);

        return $invoice->stream();
```

see more on [README.md](https://github.com/LaravelDaily/laravel-invoices/blob/master/README.md) in [General](https://github.com/LaravelDaily/laravel-invoices#general) section
