### ISSUE TITLE
Path of package views could be changed?

### ISSUE THREAD

**Issue by drbornot** [LaravelDaily/laravel-invoices#123]
Hi guys, I will just be wondering if it's possible to change the view path to another location in the project? I'm currently using Modules to organize the different modules of my app, and want to have this path into for example Modules/Frontend/Views/vendor/invoice/default.blade.php...how I can handle this?

Thanks in advance

**Comment by mc0de** [comment]
@drbornot hi, this wasn't thought at the time of development

you would need to override render() and toHtml() methods
lines of interest would be:
https://github.com/LaravelDaily/laravel-invoices/blob/88c472680951acc57ccf179711add7d8dda36821/src/Invoice.php#L256
https://github.com/LaravelDaily/laravel-invoices/blob/88c472680951acc57ccf179711add7d8dda36821/src/Invoice.php#L270

since all methods are public for this purpose there should be no problem customising that

```PHP
use LaravelDaily\Invoices\Invoice;

class MyNewInvoice extends Invoice {}
```

**Comment by mc0de** [comment]
Maybe at some point we fix this, but no promises since our schedule is pretty tight. Closing for now.

**Comment by drbornot** [comment]
> Maybe at some point we fix this, but no promises since our schedule is pretty tight. Closing for now.

Thank dude, I did it, and worked well.
