### ISSUE TITLE
Custom font

### ISSUE THREAD

**Issue by srocevas** [LaravelDaily/laravel-invoices#132]
How to add custom font to the invoice
I have tried different ways, different font types but none of them worked.
In HTML view everything looks good but after changing the method to download invoice text looks missing.

Example font import:
```
@font-face {
    font-family: 'Inter';
    font-weight: 400;
    font-style: normal;
    font-variant: normal;
    src: local('Inter'), url({{ storage_path('fonts/inter/Inter-Regular.otf') }}) format('truetype');
}

@font-face {
    font-family: 'Inter';
    font-weight: 700;
    font-style:normal;
    font-variant:normal;
    src: local('Inter'), url({{ storage_path('fonts/inter/Inter-Bold.otf') }}) format('truetype');
}

body {
    font-family: 'Inter', sans-serif;
    font-weight: 400;
}
```

**Comment by mc0de** [comment]
@srocevas for custom please refer to DomPDF https://github.com/dompdf/dompdf/issues?q=is%3Aissue+custom+font package, because it responsible for PDF rendering. Laravel Invoices wraps all invoice functionality around it.

**Comment by dodaydream** [comment]
I also have the same issue before. However, since this package relies on laravel-dompdf, which that package wraps the DomPDF library. It seems the `setOptions` method in laravel-dompdf will override the settings.

Therefore, even if you have set the font directory in `config/dompdf.php`, (in `/storage/fonts` directory by default). It will reverted to DomPdf's default, i.e. in `/vendor/dompdf/dompdf/fonts`. This results DomPDF unable to find your custom font.

I have already created a pull request on laravel-dompdf (see: https://github.com/barryvdh/laravel-dompdf/pull/846) to fix this and waiting for their approval.
