### ISSUE TITLE
Ability to add invoice path

### ISSUE THREAD

**Issue by sarunaslite** [LaravelDaily/laravel-invoices#136]
**Is your feature request related to a problem? Please describe.**
I can't choose where to save files and have a simple short filename while downloading PDFs.
This generates long ungly filename:
`->filename($invoice->team->uid . '/invoices/ . $invoice->series . $invoice->sequence);`
 I'm want to store files in separate folders for different user accounts/teams.

**Describe the solution you'd like**
It would be nice to choose where to save files:
`$invoicePackage->save($invoice->invoiceDisk(), $invoice->team->uid . '/invoices/');` (add path to save method)
or
add `->path($invoice->team->uid . '/invoices/')` for the `filename`

**Comment by mc0de** [comment]
@sarunaslite you can already do that

slightly modified snippet part from second advanced example

```php
$invoice = Invoice::make()
    ->series('BIG')
    ->status(__('invoices::invoice.paid'))
    ->sequence(667)
    ->serialNumberFormat('{SEQUENCE}/{SERIES}')
    ->seller($client)
    ->buyer($customer)
    ->date(now()->subWeeks(3))
    ->dateFormat('m/d/Y')
    ->payUntilDays(14)
    ->currencySymbol('$')
    ->currencyCode('USD')
    ->currencyFormat('{SYMBOL}{VALUE}')
    ->currencyThousandsSeparator('.')
    ->currencyDecimalPoint(',')
    ->addItems($items)
    ->notes($notes)
    ->logo(public_path('vendor/invoices/sample-logo.png'))
    // You can additionally save generated invoice to configured disk
    ->save('public');

$invoice->filename(
    sprintf( // sprintf used only just for readability but not necessary
        '%s/invoices/%s',
        auth()->id(), // can be team id,
        $invoice->series . $invoice->sequence
    ),
)
    ->save('public');
```

OR
```php
->filename(auth()->id() . '/invoices/' . $invoice->series . $invoice->sequence)
```

Invoice contents will be saved at `storage/app/public/1/invoices/BIG00667.pdf`

If you want other directory than `storage/app/public` please configure another local disk in `config/filesystems.php`. Saving to "disks" instead of paths are intentional in case you have another storage engines in backend like Amazon S3, thus brings more flexibility for various types of projects with different business requirements.

also it is good to add a prefix before any ids to have subdirectory, so you can tell what that id means, and avoid collisions in future in case you're saving it for team or user separately

```php
$invoice->filename(
    sprintf(
        'user/%s/invoices/%s', // <- with prefix user as a subdirectory
        auth()->id(), // can be team id,
        $invoice->series . $invoice->sequence
    ),
)
    ->save('public');
```

> Note: generally it is good idea to serve invoices via controllers and check for permissions first, instead of plain urls

**Comment by mc0de** [comment]
@sarunaslite to add, you can completely ignore methods provided by package

```php
// logic before

$invoice->render(); // render method generates actual pdf data and then $invoice->output is no longer null

Storage::disk('s3')->put('/transports/', 'any name you like.pdf', $invoice->output);

// OR

file_put_contents('/path/to/filename', $invoice->output);

```

**Comment by srocevas** [comment]
Thank you @mc0de for a quick answer. To use render() solved my problem, Thanks
