### ISSUE TITLE
Rounding Error

### ISSUE THREAD

**Issue by henner1979** [LaravelDaily/laravel-invoices#190]
**Describe the bug**
Sometimes there are rounding errors when invoices are generated.

**To Reproduce**
(1) Create an invoice-line with the following details:
- Quantity: 41,131.74
- Net-Amount: 0.06

(2) Create an invoice with the following details:
- VAT rate: 19%

(3) Show the VAT amount using $invoice->formatCurrency($invoice->total_taxes)
- VAT amount: 468.90

**Expected behavior**
The following values should appear on the invoice:
- VAT amount: 468.91

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Microsoft Edge
 - Version: 112.0.1722.68 (Offizielles Build) (64-Bit)

**Comment by deshiloh** [comment]
I also have the problem

**Comment by mc0de** [comment]
@henner1979 @deshiloh this is not a bug. all values are correct and summed properly.

im not sure why you expect to have 468.91.

```
41131.74 * 0.06 = 2467.9044
```

the item price gets rounded to `2467.90`, the VAT price is calculated based on that.

```
2467.90 * 0.19 = 468.901
// rounded to 468.90
```

everything else is just sums if these item values.

---

even if you didn't do ANY rounding at all there would still be 468.90 when you round it.

```
41131.74 * 0.06 * 0.19 = 468.901836
```

could you explain better what the issue is?
