### ISSUE TITLE
Adding css "break-inside: auto;"

### ISSUE THREAD

**Issue by DavidRodriguezPerez** [LaravelDaily/laravel-invoices#201]
Could it be possible to add a new argument to it so we can add this css "break-inside: auto;"?? 

This is related to page break

ref: https://developer.mozilla.org/en-US/docs/Web/CSS/break-inside

**Comment by mc0de** [comment]
could you explain?

**Comment by Jared-ElAyudante** [comment]
![break-inside](https://github.com/LaravelDaily/laravel-invoices/assets/143093786/e5bb5a31-3c92-429a-9fdb-bf90390e79c7)
![break-inside1](https://github.com/LaravelDaily/laravel-invoices/assets/143093786/a44d324c-08a8-4c92-bb97-69396f73ebcd)
I'm having the same issue, I want to use the CSS property of "break-inside", because by default invoice is using the "break-inside: avoid;", and I hope this functionality to be implemented... =>"break-inside: auto;"; for more references I send 2 images, the first one called break-inside is using the value of "break-inside: auto;", and the second one called break-inside1, is using the value of "break-inside: avoid".
Why I think it should be added? 
Firstly, because we use tables to put the content, when a table has a lot of text, as an example, a description of a product or maybe the description of a work is put inside, but we keep adding more <td>, at some point automatically it does a "break-inside: avoid;", I don't really know if it's implemented, but it could be nice if the content doesn't start printing in the next page, it leaves a lot of white space wasted.

**Comment by mc0de** [comment]
I think is very specific, on other hand, what can i see from images, a lot of white space was moved to previous page and probably could be solved in the template itself and has been answered several times #30
