### ISSUE TITLE
Remove 'Please pay until'

### ISSUE THREAD

**Issue by gidaban** [LaravelDaily/laravel-invoices#21]
For example i am using package for generate invoice on fly when customer has been charged by stripe. Then invoice is already paid. 

**Describe the solution you'd like**
Maybe something like that ` ->payUntilDays(null)` ? It will means already paid ?

**Comment by PovilasKorop** [comment]
@gidaban thanks for the suggestion. Currently we are busy on other projects, so no time for adding this functionality, but we are accepting pull requests if you are willing to contribute.

**Comment by gidaban** [comment]
@PovilasKorop unfortunately i never did it before :)

**Comment by PovilasKorop** [comment]
@gidaban it's pretty easy to learn, and would be really beneficial for your development career :)

**Comment by chendicott** [comment]
@gidaban a quick way you could do this is to create a new template rather than the default, and then remove the section that adds the 'Please pay until' wording.

Example:

1. Copy `/views/vendor/invoices/templates/default.blade.php` to the same folder named `invoice.blade.php`
2. Where you're generating your invoice add `->template("invoice")`
3. In `invoice.blade.php` remove the following section 
`<p>{{ trans('invoices::invoice.pay_until') }}: {{ $invoice->getPayUntilDate() }}</p>`

**Comment by mc0de** [comment]
as @chendicott described, edit template and hide what you don't need, no additional functionality needed

**Comment by gidaban** [comment]
@chendicott I really know how to modify it in blade file. In this case 2 blade files are required :) If something is paid already. 

@chendicott i will modify as i need it thanks
