### ISSUE TITLE
japanese characters not displaying properly

### ISSUE THREAD

**Issue by geskeitaloricardo** [LaravelDaily/laravel-invoices#24]
displaying squares instead of japanese characters!
I tried to change the font in default.blade.php but I'm getting ??? now

here is the result
<img width="369" alt="Untitled" src="https://user-images.githubusercontent.com/30541779/84100913-cbfd5a80-aa47-11ea-82a7-7a0879b9c1ba.png">

here is my lang file
`

    'serial'          => 'シリアル番号',
    'date'            => '請求日付',
    'seller'          => '売り手',
    'buyer'           => '買い手',
    'address'         => '住所',
    'code'            => 'Code',
    'vat'             => 'VAT code',
    'phone'           => '電話番号',
    'description'     => '詳細',
    'units'           => '単位',
    'quantity'        => '数量',
    'price'           => '価格',
    'discount'        => '割引',
    'tax'             => '税金',
    'sub_total'       => '小計',
    'total_discount'  => '合計割引',
    'taxable_amount'  => '課税額',
    'total_taxes'     => '合計税',
    'tax_rate'        => '税率',
    'total_amount'    => '合計金額',
    'pay_until'       => 'お支払い締め切り',
    'amount_in_words' => '文字金額',
    'notes'           => '備考',
    'shipping'        => '送料',
`

Any ideas?

**Comment by PovilasKorop** [comment]
@geskeitaloricardo you need to look for the font that would display Japanese characters in PDF. Sorry, but we haven't tested the PDFs in all the world's languages.

**Comment by mc0de** [comment]
Hi @geskeitaloricardo 

By default distributed fonts do not support all possible symbols in the world.

Since this is an issue not on our end we can provide a bit of information how to set it up for you:

More info how to install your font with support: https://github.com/dompdf/dompdf/wiki/UnicodeHowTo#load-a-font-supporting-your-characters-into-dompdf

    Note: that dompdf is allready installed, so you might need to use only dompdf-utils project

Also, you can find more information which font supports your symbol by googling.
One of the results: http://www.fileformat.info/info/unicode/char/9f3/fontsupport.htm
