### ISSUE TITLE
Unable to set currency other than USD and Euro

### ISSUE THREAD

**Issue by Xatta-Trone** [LaravelDaily/laravel-invoices#5]
I have tried to use this symbol and currency code but in final pdf it shows nothing but a box.
currency tried to use ৳(BDT) https://www.fileformat.info/info/unicode/char/09f3/index.htm

**Comment by PovilasKorop** [comment]
@Xatta-Trone thanks for reporting, we will schedule to investigate in a week or so, now have a lot of client work after Christmas break, so can't do it quicker.

**Comment by mc0de** [comment]
@Xatta-Trone 

Hi,

By default distributed fonts do not support this currency symbol.

Since this is an issue not on our end we can provide a bit of information how to set it up for you:

More info how to install your font with support: https://github.com/dompdf/dompdf/wiki/UnicodeHowTo#load-a-font-supporting-your-characters-into-dompdf

> Note: that dompdf is allready installed, so you might need to use only [dompdf-utils project](https://github.com/dompdf/utils)

Also, you can find more information which font supports your symbol by googling.
One of the results: http://www.fileformat.info/info/unicode/char/9f3/fontsupport.htm
